import img from "../assets/images/immu-milk.png";

const allProducts = {
  category: "All Products",
  // category: 'Spices',
  // category: 'Blends',
  // category: 'Mixes',
  // category: 'Beverages',
  // category: 'Soup & Noodles',
  products: [
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
    { id: "223", title: "Immu Milk", image: img, price: "120", weight: "100" },
  ],
  filters: [
    { title: "Price" },
    { title: "Weight" },
    { title: "Category" },
    { title: "Quantity" },
    { title: "Offers" },
    { title: "Sale" },
    { title: "Special" },
    { title: "Out of stock" },
  ],
  categories: [
    {
      title: "All Products",
      products: [
        { product_id: 1, title: "Rasam Mix", image: img },
        { product_id: 2, title: "Dosa Mix", image: img },
        { product_id: 3, title: "Atta Mix", image: img },
        { product_id: 4, title: "Noodles Mix", image: img },
        { product_id: 5, title: "Rasam Mix", image: img },
        { product_id: 6, title: "Rasam Mix", image: img },
        { product_id: 7, title: "Dosa Mix", image: img },
        { product_id: 8, title: "Atta Mix", image: img },
        { product_id: 9, title: "Noodles Mix", image: img },
        { product_id: 10, title: "Rasam Mix", image: img },
      ],
    },
    {
      title: "Spice blends",
      products: [
        { product_id: 1, title: "Rasam Mix", image: img },
        { product_id: 2, title: "Dosa Mix", image: img },
        { product_id: 3, title: "Atta Mix", image: img },
        { product_id: 4, title: "Noodles Mix", image: img },
        { product_id: 5, title: "Rasam Mix", image: img },
        { product_id: 6, title: "Rasam Mix", image: img },
      ],
    },
    {
      title: "Flour Packs",
      products: [
        { product_id: 1, title: "Rasam Mix", image: img },
        { product_id: 2, title: "Dosa Mix", image: img },
        { product_id: 3, title: "Atta Mix", image: img },
      ],
    },
    {
      title: "Dosa Mix",
      products: [
        { product_id: 1, title: "Rasam Mix", image: img },
        { product_id: 2, title: "Dosa Mix", image: img },
        { product_id: 3, title: "Atta Mix", image: img },
        { product_id: 4, title: "Noodles Mix", image: img },
        { product_id: 5, title: "Rasam Mix", image: img },
        { product_id: 6, title: "Rasam Mix", image: img },
      ],
    },
    {
      title: "Rasam & Soup",
      products: [
        { product_id: 1, title: "Rasam Mix", image: img },
        { product_id: 2, title: "Dosa Mix", image: img },
        { product_id: 3, title: "Atta Mix", image: img },
        { product_id: 4, title: "Noodles Mix", image: img },
        { product_id: 5, title: "Rasam Mix", image: img },
      ],
    },
    {
      title: "Noodle & Pasta",
      products: [
        { product_id: 1, title: "Rasam Mix", image: img },
        { product_id: 2, title: "Dosa Mix", image: img },
        { product_id: 3, title: "Atta Mix", image: img },
      ],
    },
    {
      title: "Bevarage Mixes",
      products: [
        { product_id: 1, title: "Rasam Mix", image: img },
        { product_id: 2, title: "Dosa Mix", image: img },
        { product_id: 3, title: "Atta Mix", image: img },
        { product_id: 4, title: "Noodles Mix", image: img },
        { product_id: 5, title: "Rasam Mix", image: img },
        { product_id: 6, title: "Rasam Mix", image: img },
      ],
    },
    {
      title: "Health Mix",
      products: [
        { product_id: 1, title: "Rasam Mix", image: img },
        { product_id: 2, title: "Dosa Mix", image: img },
        { product_id: 3, title: "Atta Mix", image: img },
      ],
    },
  ],
};

export default allProducts;
